version: "3.7"

services:
  backend:
    build:
      context: ./node_backend
      dockerfile: Dockerfile.dev
    container_name: "${APP_NAME}-backend"
    restart: always
    env_file: .env
    volumes:
      - type: bind
        source: ./node_backend/src
        target: /usr/src/app/src
    expose: 
      - "${API_PORT}"
    ports: 
      - "${API_PORT}:${API_PORT}"
    command: npm run dev
    environment: 
      - PORT=${API_PORT}
      - DB_URL=mongodb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    env_file: .env
    container_name: "${APP_NAME}-database"
    ports:
      - '27017:27017'
  frontend:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile.dev
    container_name: "${APP_NAME}-frontend"
    env_file: .env
    expose:
      - "${CLIENT_PORT}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - type: bind
        source: ./react_frontend/src
        target: /usr/src/app/src
      - type: bind
        source: ./react_frontend/public
        target: /usr/src/app/public
    command: npm start